name: frontend-ci
  
on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build: 
    runs-on: ubuntu-latest
    
    steps: 
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with: 
          node-version: 22
      
      - name: Install Dependencies
        working-directory: ./todo-app
        run: npm install

      - name: Build Project
        working-directory: ./todo-app
        run: npm run build

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./todo-app/dist

  
